// <auto-generated />
using DataAccessRepository.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace DataRepository.Migrations
{
    [DbContext(typeof(TravDeskDbcontext))]
    [Migration("20180529182341_ninth")]
    partial class ninth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessRepository.Entities.BoardingLodgingInfo", b =>
                {
                    b.Property<int>("BoardingInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AmountSpent");

                    b.Property<string>("Currency");

                    b.Property<int>("Eligibility");

                    b.Property<DateTime>("FromDate");

                    b.Property<string>("PlaceofStay");

                    b.Property<int>("ReimbursementInfoId");

                    b.Property<string>("Remarks");

                    b.Property<DateTime>("ToDate");

                    b.Property<double>("Total");

                    b.HasKey("BoardingInfoId");

                    b.HasIndex("ReimbursementInfoId");

                    b.ToTable("BoardingLodgingInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Gender");

                    b.Property<string>("IdentityId");

                    b.Property<string>("Locale");

                    b.Property<string>("Location");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.FareInfo", b =>
                {
                    b.Property<int>("FareInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AmountSpent");

                    b.Property<string>("Currency");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Eligibility");

                    b.Property<string>("From");

                    b.Property<int>("ReimbursementInfoId");

                    b.Property<string>("Remark");

                    b.Property<string>("To");

                    b.Property<double>("Total");

                    b.Property<string>("TravelMode");

                    b.HasKey("FareInfoId");

                    b.HasIndex("ReimbursementInfoId");

                    b.ToTable("FareInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.FlightInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("FlightCost");

                    b.Property<string>("FlightDirection");

                    b.Property<string>("FlightFrom");

                    b.Property<string>("FlightItemId");

                    b.Property<string>("FlightName");

                    b.Property<string>("FlightTo");

                    b.Property<int>("RequestInfoId");

                    b.HasKey("Id");

                    b.HasIndex("RequestInfoId");

                    b.ToTable("FlightInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.ForexInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CardExpiryDate");

                    b.Property<string>("CardNumber");

                    b.Property<string>("CardType");

                    b.Property<int>("RequestInfoId");

                    b.HasKey("Id");

                    b.HasIndex("RequestInfoId");

                    b.ToTable("ForexInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.HotelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Amenities");

                    b.Property<DateTime>("CheckinTime");

                    b.Property<DateTime>("CheckoutTime");

                    b.Property<string>("HotelName");

                    b.Property<string>("Location");

                    b.Property<string>("MobileNo");

                    b.Property<double>("Price");

                    b.Property<int>("RequestInfoId");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.HasIndex("RequestInfoId");

                    b.ToTable("HotelInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.LocalTravelExpenseInfo", b =>
                {
                    b.Property<int>("LocalTravelExpenseInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AmountSpent");

                    b.Property<double>("Currency");

                    b.Property<DateTime>("Date");

                    b.Property<string>("From");

                    b.Property<string>("ModeofConveyance");

                    b.Property<int>("ReimbursementInfoId");

                    b.Property<bool>("SupportbyVoucher");

                    b.Property<string>("To");

                    b.Property<double>("Total");

                    b.HasKey("LocalTravelExpenseInfoId");

                    b.HasIndex("ReimbursementInfoId");

                    b.ToTable("LocalTravelExpenseInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.OtherExpensesInfo", b =>
                {
                    b.Property<int>("OtherExpensesInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AmountSpent");

                    b.Property<string>("Currency");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Eligibility");

                    b.Property<string>("NatureofExpense");

                    b.Property<int>("ReimbursementInfoId");

                    b.Property<bool>("SupportbyVoucher");

                    b.Property<double>("Total");

                    b.HasKey("OtherExpensesInfoId");

                    b.HasIndex("ReimbursementInfoId");

                    b.ToTable("OtherExpensesInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.PassportInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("PassportExpiryDate");

                    b.Property<string>("PassportNumber");

                    b.Property<int>("RequestInfoId");

                    b.Property<DateTime?>("VisaExpiryDate");

                    b.Property<string>("VisaNumber");

                    b.HasKey("Id");

                    b.HasIndex("RequestInfoId")
                        .IsUnique();

                    b.ToTable("PassportInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.PerDiemInfo", b =>
                {
                    b.Property<int>("PerDiemInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ArrivalDate");

                    b.Property<string>("Currency");

                    b.Property<DateTime>("DepartureDate");

                    b.Property<int>("Eligibility");

                    b.Property<int>("ReimbursementInfoId");

                    b.Property<string>("Remarks");

                    b.Property<double>("Total");

                    b.Property<double>("TotalAmount");

                    b.Property<int>("TotalDays");

                    b.HasKey("PerDiemInfoId");

                    b.HasIndex("ReimbursementInfoId");

                    b.ToTable("PerDiemInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.ReimbursementInfo", b =>
                {
                    b.Property<int>("ReimbursementInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AnyOtherExpenseReimbursed");

                    b.Property<string>("BandWorkLevel");

                    b.Property<string>("ClientName");

                    b.Property<string>("CostCenter");

                    b.Property<DateTime>("DateofArrival");

                    b.Property<DateTime>("DateofDeparture");

                    b.Property<string>("Designation");

                    b.Property<string>("EmployeeId");

                    b.Property<string>("EmployeeName");

                    b.Property<bool>("FlightChargesReimbursed");

                    b.Property<string>("LocationofTravel");

                    b.Property<string>("ProjectCode");

                    b.Property<string>("PurposeofTravel");

                    b.Property<string>("ReimbursementStatus");

                    b.Property<bool>("TravelBillabletoCustomer");

                    b.Property<bool>("TravelExpenseReimbursed");

                    b.HasKey("ReimbursementInfoId");

                    b.ToTable("ReimbursementInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.RequestInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Approver");

                    b.Property<DateTime>("Dob");

                    b.Property<string>("EmployeeId");

                    b.Property<string>("EmployeeName");

                    b.Property<string>("ManagerId");

                    b.Property<string>("ManagerName");

                    b.Property<string>("ProjectId");

                    b.Property<string>("RequestStatus");

                    b.Property<string>("TravelCountry");

                    b.Property<DateTime>("TravelReturn");

                    b.Property<DateTime>("TravelStart");

                    b.HasKey("Id");

                    b.ToTable("RequestInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.TravelExpensesWithoutVoucherInfo", b =>
                {
                    b.Property<int>("TravelExpensesWithoutVoucherInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AmountSpent");

                    b.Property<string>("Currency");

                    b.Property<DateTime>("Date");

                    b.Property<string>("From");

                    b.Property<string>("ModeofConveyance");

                    b.Property<int>("ReimbursementInfoId");

                    b.Property<string>("Remarks");

                    b.Property<string>("To");

                    b.Property<double>("Total");

                    b.HasKey("TravelExpensesWithoutVoucherInfoId");

                    b.HasIndex("ReimbursementInfoId");

                    b.ToTable("TravelExpensesWithoutVoucherInfo");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.TravelExpensesWithVoucherInfo", b =>
                {
                    b.Property<int>("TravelExpensesWithVoucherInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AmountSpent");

                    b.Property<string>("Currency");

                    b.Property<DateTime>("Date");

                    b.Property<string>("From");

                    b.Property<string>("ModeofConveyance");

                    b.Property<int>("ReimbursementInfoId");

                    b.Property<string>("Remarks");

                    b.Property<string>("To");

                    b.Property<double>("Total");

                    b.HasKey("TravelExpensesWithVoucherInfoId");

                    b.HasIndex("ReimbursementInfoId");

                    b.ToTable("TravelExpensesWithVoucherInfo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<long?>("FacebookId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PictureUrl");

                    b.ToTable("AppUser");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.BoardingLodgingInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.ReimbursementInfo", "ReimbursementInfo")
                        .WithMany("BoardingLodgingExpenseInfo")
                        .HasForeignKey("ReimbursementInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.Customer", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.AppUser", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId");
                });

            modelBuilder.Entity("DataAccessRepository.Entities.FareInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.ReimbursementInfo", "ReimbursementInfo")
                        .WithMany("FareInfo")
                        .HasForeignKey("ReimbursementInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.FlightInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.RequestInfo", "RequestInfo")
                        .WithMany("FlightInfo")
                        .HasForeignKey("RequestInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.ForexInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.RequestInfo", "RequestInfo")
                        .WithMany("ForexInfo")
                        .HasForeignKey("RequestInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.HotelInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.RequestInfo", "RequestInfo")
                        .WithMany("HotelInfo")
                        .HasForeignKey("RequestInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.LocalTravelExpenseInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.ReimbursementInfo", "ReimbursementInfo")
                        .WithMany("LocalTravelExpenseInfo")
                        .HasForeignKey("ReimbursementInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.OtherExpensesInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.ReimbursementInfo", "ReimbursementInfo")
                        .WithMany("OtherExpenseInfo")
                        .HasForeignKey("ReimbursementInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.PassportInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.RequestInfo", "RequestInfo")
                        .WithOne("PassportInfo")
                        .HasForeignKey("DataAccessRepository.Entities.PassportInfo", "RequestInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.PerDiemInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.ReimbursementInfo", "ReimbursementInfo")
                        .WithMany("PerdiemInfo")
                        .HasForeignKey("ReimbursementInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.TravelExpensesWithoutVoucherInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.ReimbursementInfo", "ReimbursementInfo")
                        .WithMany("TravelExpenseUnsupportedbyVoucherInfo")
                        .HasForeignKey("ReimbursementInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataAccessRepository.Entities.TravelExpensesWithVoucherInfo", b =>
                {
                    b.HasOne("DataAccessRepository.Entities.ReimbursementInfo", "ReimbursementInfo")
                        .WithMany("TravelExpensebyVoucherInfo")
                        .HasForeignKey("ReimbursementInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
